---CREDITS: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/linting/eslint.lua

local auto_format = vim.g.lazyvim_eslint_auto_format == nil or vim.g.lazyvim_eslint_auto_format

return {
  -- {
  --   "mfussenegger/nvim-lint",
  --   optional = true,
  --   opts = {
  --     linters_by_ft = {
  --       javascript = { "eslint_d" },
  --       typescript = { "eslint_d" },
  --       javascriptreact = { "eslint_d" },
  --       typescriptreact = { "eslint_d" },
  --     },
  --   },
  -- },
  -- {
  --   "neovim/nvim-lspconfig",
  --   -- other settings removed for brevity
  --   opts = {
  --     ---@type lspconfig.options
  --     servers = {
  --       eslint_d = {
  --         settings = {
  --           -- helps eslint find the eslintrc when it's placed in a subfolder instead of the cwd root
  --           workingDirectories = { mode = "auto" },
  --           format = auto_format,
  --         },
  --       },
  --     },
  --     setup = {
  --       eslint_d = function()
  --         if not auto_format then
  --           return
  --         end
  --
  --         local function get_client(buf)
  --           return LazyVim.lsp.get_clients({ name = "eslint_d", bufnr = buf })[1]
  --         end
  --
  --         local formatter = LazyVim.lsp.formatter({
  --           name = "eslint_d: lsp",
  --           primary = false,
  --           priority = 200,
  --           filter = "eslint_d",
  --         })
  --
  --         -- Use EslintFixAll on Neovim < 0.10.0
  --         if not pcall(require, "vim.lsp._dynamic") then
  --           formatter.name = "eslint_d: EslintFixAll"
  --           formatter.sources = function(buf)
  --             local client = get_client(buf)
  --             return client and { "eslint_d" } or {}
  --           end
  --           formatter.format = function(buf)
  --             local client = get_client(buf)
  --             if client then
  --               local diag = vim.diagnostic.get(buf, { namespace = vim.lsp.diagnostic.get_namespace(client.id) })
  --               if #diag > 0 then
  --                 vim.cmd("EslintFixAll")
  --               end
  --             end
  --           end
  --         end
  --
  --         -- register the formatter with LazyVim
  --         LazyVim.format.register(formatter)
  --       end,
  --     },
  --   },
  -- },
}
