return {
  -- {
  --   "supermaven-inc/supermaven-nvim",
  --   config = function()
  --     require("supermaven-nvim").setup({
  --       keymaps = {
  --         accept_suggestion = "<C-]>",
  --         clear_suggestion = "<C-\\>",
  --         accept_word = "<C-[>",
  --       },
  --     })
  --   end,
  -- },
  -- {
  --   "nvim-cmp",
  --   opts = function(_, opts)
  --     table.insert(opts.sources, 1, {
  --       name = "supermaven",
  --       group_index = 1,
  --       priority = 100,
  --     })
  --   end,
  -- },
}
